In [1]:
import numpy as np
import seaborn as sns

In [2]:
cadeia = np.load("cadeira.npy")

In [3]:
print(cadeia)

[[[69.59538897  0.29209903]
  [69.59596077  0.29228179]
  [69.59576969  0.29201858]
  ...
  [69.59546143  0.29189181]
  [69.59587699  0.29204804]
  [69.59564585  0.291965  ]]

 [[69.59546588  0.29209268]
  [69.59607835  0.2921245 ]
  [69.59566865  0.29216774]
  ...
  [69.59546143  0.29189181]
  [69.59590115  0.29205672]
  [69.59565152  0.29197325]]

 [[69.59546478  0.2920535 ]
  [69.59597839  0.29210081]
  [69.59573965  0.29223831]
  ...
  [69.59545005  0.29189504]
  [69.59594954  0.2921655 ]
  [69.59567335  0.29199348]]

 ...

 [[70.40200944  0.28005922]
  [69.95215091  0.28183249]
  [67.0915346   0.31153567]
  ...
  [68.85505969  0.30948036]
  [68.17805856  0.29149164]
  [68.24534076  0.29419525]]

 [[69.80831806  0.28986384]
  [69.95215091  0.28183249]
  [66.87790377  0.31824152]
  ...
  [69.06151907  0.31624855]
  [68.17805856  0.29149164]
  [67.28535857  0.30958126]]

 [[69.60687895  0.28956122]
  [69.95215091  0.28183249]
  [66.24574437  0.32572833]
  ...
  [69.06151907  0.316248